### ISSUE TITLE
logout from Not-Twitter app when reload the tab

### ISSUE THREAD

**Issue by safesurfer** [joshuef/webIdManager#14]
we will be logging out from Not-Twitter app when we reload the tab in the browser

**Comment by joshuef** [comment]
I'm not sure if this is an issue or desired behaviour. 

I think we should be looking at how we want the UX to be before making decisions/changes on these things tbh.

**Comment by joshuef** [comment]
This has been addressed via peruse with webIds now being set per tab. So if you have one set and reload, it will be applied to the app.

(Though it won't necesasrily log you in if you have disabled automatic re auth, that's expected behaviour.)
