### ISSUE TITLE
able to create an empty post with just a whitespace in the input fields in Not-Twitter app

### ISSUE THREAD

**Issue by safesurfer** [joshuef/webIdManager#15]
I'm able to create an empty post with just a whitespace in `summary`, `content` input fields in Not-Twitter app and also in WebID manager too, `name` and `nick name` input fields accept whitespace as an input, also not able to edit the webid created with whitespace

**Comment by joshuef** [comment]
all things in webidmanager are now `trimmed`. 
Post field is required and requires non whitespace text.

**Comment by joshuef** [comment]
ffeb9f5386d6cac2133d1eceba5d6a5611df5fb8
