### ISSUE TITLE
It is possible to create ID with an incorrect name

### ISSUE THREAD

**Issue by nbaksalyar** [joshuef/webIdManager#2]
Currently, I can create an ID that I won't be able to request in Peruse.

E.g. `safe:///nikita` (with an extra slash in the beginning) or `safe://nikita/////`

**Comment by happybeing** [comment]
I filed a related issue about correct WebID format: #4

**Comment by joshuef** [comment]
The first, we're blocking via regex check in app. (Both actually resolve fine in peruse, though agreed, less than desireable).

This is best handled by the safe_app_nodejs apis to provide true validation on the ids.
