### ISSUE TITLE
webid link doesn't open without the service part in the URI

### ISSUE THREAD

**Issue by hitman401** [joshuef/webIdManager#5]
If I create a web id as `safe://krishna` the webid gets created and listed successfully. When clicked on the link, it says `service not found`

**Comment by bochaco** [comment]
This was listed as a known limitation, so this is indeed an issue yet.

**Comment by joshuef** [comment]
This is being prevented at the app layer via regex now. A subdomain must be specified.

I've created an issue in safe_app_nodejs for a real implementation of default services containers: https://github.com/maidsafe/safe_app_nodejs/issues/255
